name: ci

on:
  push:
    branches:
#      - main
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: LogIn to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install dependencies and run tests
        working-directory: bemediasearch
        run:  chmod +x mvnw && sed -i "s/\r$//" mvnw && ./mvnw test

      -
        name: Build and push BE
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: idtruoc/bemedia:latest
          context: "{{defaultContext}}:bemediasearch"

      - name: Build and push FE
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: idtruoc/femedia:latest
          context: "{{defaultContext}}:femediasearch"


      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}


      - name: Build and deploy Container App BE
        uses: azure/container-apps-deploy-action@v1
        with:
          containerAppName: bemedia
          resourceGroup: media
          imageToDeploy: docker.io/idtruoc/bemedia:latest

      - name: Build and deploy Container App FE
        uses: azure/container-apps-deploy-action@v1
        with:
          containerAppName: femedia
          resourceGroup: media
          imageToDeploy: docker.io/idtruoc/femedia:latest