name: ci

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
#      -
#        name: Set up QEMU
#        uses: docker/setup-qemu-action@v3
#      -
#        name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v3
      -
        name: Build and push fe
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: idtruoc/femedia:latest
          context: "{{defaultContext}}:femediasearch"
#          file: ./femediasearch/Dockerfile
